; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_src_filter = +<*> +<**/*.c> +<**/*.cpp>

extra_scripts=
  pre:scripts/prebuild.py
;  post:scripts/postbuild.py
; disabled because i end up opening screen myself anyway

[env:node-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
; -DNO_GLOBAL_INSTANCES
; TODO: update logging framework to not require Serial
; so that NO_GLOBAL_INSTANCES can be re-enabled
